### ISSUE TITLE
Anda el autotarget en aq (citadel)?

### ISSUE THREAD

**Issue by Montinhos** [Loliconera/tera-guide-spanish#2]
Al momento de entrar a esa nueva dungeon me aparece los titulos en español pero no me aparece el autotarget.

**Comment by Loliconera** [comment]
auto target?

**Comment by Montinhos** [comment]
si, anda en esa nueva dungeon?

**Comment by Loliconera** [comment]
se supone que el autotarget es un modulo aparte de este modulo llamado tera guide

**Comment by Montinhos** [comment]
pero si el autotarget si estaba en tu modulo loli, no estaria entendiendo xdd

**Comment by Loliconera** [comment]
el autotarget no viene con mi modulo

**Comment by Loliconera** [comment]
mi modulo solo envía mensajes en la pantalla y spamea item y zonas de ataques del boss en el suelo

**Comment by Loliconera** [comment]
se agrego la guia para Citadel
